// Mock data for the application
// This would typically come from a database

export const highlightsProducts = [
  {
    _id: "1",
    name: "Headphones",
    title: "Premium Sound Quality",
    buttonTitle: "Shop Now",
    _base: "headphones",
    image: "/images/bannerOne.webp",
    color: "#ffffff",
  },
  {
    _id: "2",
    name: "Smartphones",
    title: "Latest Technology",
    buttonTitle: "View Collection",
    _base: "cellPhones",
    image: "/images/bannerTwo.webp",
    color: "#ffffff",
  },
  {
    _id: "3",
    name: "Power Banks",
    title: "Stay Charged Anywhere",
    buttonTitle: "Explore",
    _base: "accessories",
    image: "/images/bannerThree.webp",
    color: "#ffffff",
  },
]

export const blogsData = [
  {
    _id: "1",
    title: "The Future of Wearable Tech",
    _base: "Technology",
    image: "/images/bannerOne.webp",
  },
  {
    _id: "2",
    title: "How to Choose the Right Headphones",
    _base: "Guides",
    image: "/images/discountImgOne.png",
  },
  {
    _id: "3",
    title: "Top 10 Gadgets of 2023",
    _base: "Reviews",
    image: "/images/bannerTwo.webp",
  },
]

export const categories = [
  {
    _id: "1",
    name: "Headphones",
    _base: "headphones",
    image: "/images/bannerOne.webp",
  },
  {
    _id: "2",
    name: "Smart Watches",
    _base: "smartWatches",
    image: "/images/bannerThree.webp",
  },
  {
    _id: "3",
    name: "Cameras",
    _base: "camerasAndPhotos",
    image: "/images/discountImgTwo.webp",
  },
  {
    _id: "4",
    name: "TV & Audio",
    _base: "tvAndAudio",
    image: "/images/discountImgOne.png",
  },
  {
    _id: "5",
    name: "Computers & Laptops",
    _base: "computersAndLaptop",
    image: "/images/bannerTwo.webp",
  },
  {
    _id: "6",
    name: "Graphics Cards",
    _base: "graphicsCards",
    image: "/images/cartegraphique.jpeg",
  },
]

export const products = [
  {
    _id: "1",
    name: "Sony WH-1000XM4 Wireless Headphones",
    description: "Premium wireless headphones with industry-leading noise cancellation",
    regularPrice: 349.99,
    discountedPrice: 299.99,
    image: "/images/bannerOne.webp",
    category: "headphones",
    _base: "headphones",
    isNew: true,
    quantity: 1,
    brand: "Sony",
  },
  {
    _id: "2",
    name: "Xiaomi Redmi Note 10 Pro",
    description: "Advanced smartphone with 108MP camera and AMOLED display",
    regularPrice: 299.99,
    discountedPrice: 249.99,
    image: "/images/bannerTwo.webp",
    category: "cellPhones",
    _base: "cellPhones",
    isNew: true,
    quantity: 1,
    brand: "Xiaomi",
  },
  {
    _id: "3",
    name: "Xiaomi 10000mAh Power Bank",
    description: "Portable fast-charging power bank with dual USB ports",
    regularPrice: 49.99,
    discountedPrice: 39.99,
    image: "/images/bannerThree.webp",
    category: "accessories",
    _base: "accessories",
    isNew: false,
    quantity: 1,
    brand: "Xiaomi",
  },
  {
    _id: "4",
    name: "Xiaomi Mi Air Purifier 3H",
    description: "Smart air purifier with HEPA filter and app control",
    regularPrice: 199.99,
    discountedPrice: 169.99,
    image: "/images/homeBanner.jpg",
    category: "homeAppliances",
    _base: "homeAppliances",
    isNew: false,
    quantity: 1,
    brand: "Xiaomi",
  },
  {
    _id: "5",
    name: "MSI GeForce RTX 3080 Gaming X Trio",
    description: "High-performance graphics card for gaming and content creation",
    regularPrice: 899.99,
    discountedPrice: 799.99,
    image: "/images/cartegraphique.jpeg",
    category: "graphicsCards",
    _base: "graphicsCards",
    isNew: true,
    quantity: 1,
    brand: "MSI",
  },
  {
    _id: "6",
    name: "Designer Sunglasses",
    description: "Premium sunglasses with UV protection and stylish design",
    regularPrice: 129.99,
    discountedPrice: 99.99,
    image: "/images/discountImgTwo.webp",
    category: "accessories",
    _base: "accessories",
    isNew: true,
    quantity: 1,
    brand: "Ray-Ban",
  },
  {
    _id: "7",
    name: "JBL Flip 5 Portable Bluetooth Speaker",
    description: "Waterproof portable speaker with exceptional sound quality",
    regularPrice: 119.99,
    discountedPrice: 89.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "audio",
    _base: "tvAndAudio",
    isNew: true,
    quantity: 1,
    brand: "JBL",
  },
  {
    _id: "8",
    name: 'LG 55" 4K OLED Smart TV',
    description: "Premium OLED TV with stunning picture quality and smart features",
    regularPrice: 1299.99,
    discountedPrice: 1099.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "tv",
    _base: "tvAndAudio",
    isNew: false,
    quantity: 1,
    brand: "LG",
  },
  {
    _id: "9",
    name: "Marshall Major IV Wireless Headphones",
    description: "Iconic design with over 80 hours of wireless playtime",
    regularPrice: 149.99,
    discountedPrice: 129.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "headphones",
    _base: "headphones",
    isNew: true,
    quantity: 1,
    brand: "Marshall",
  },
  {
    _id: "10",
    name: "LEEHUR Gaming Keyboard",
    description: "Mechanical gaming keyboard with RGB backlighting",
    regularPrice: 79.99,
    discountedPrice: 59.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "accessories",
    _base: "accessories",
    isNew: false,
    quantity: 1,
    brand: "LEEHUR",
  },
]
